# Generated by Django 5.0.4 on 2024-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writtenquestion',
            name='answers',
        ),
        migrations.DeleteModel(
            name='writtenanswer',
        ),
    ]
