# Generated by Django 5.0.4 on 2024-04-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('additional_students', models.ManyToManyField(related_name='additional_students', to='UserType.student', verbose_name='Additional students')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserType.fakultet', verbose_name='Fakultet')),
                ('students', models.ManyToManyField(to='UserType.student', verbose_name='Students')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Subject name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserType.fakultet', verbose_name='Fakultet')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.group', verbose_name='Group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserType.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
            },
        ),
    ]
